server:
  port: 19990
  servlet:
    context-path:
spring:
  thymeleaf:
    prefix: classpath:/templates/
    suffix:
    mode: HTML
    encoding: UTF-8
    servlet:
      content-type: text/html
    cache: false
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc\:mysql\://localhost\:3306/january?useUnicode\=true&characterEncoding\=utf-8&autoReconnect\=true&useSSL\=false&allowPublicKeyRetrieval=true
    username: root
    password: 666666
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: smile.wangsy.january.sso.model